# Generated by Django 4.1.5 on 2023-01-31 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(default='pending', max_length=100, null=True)),
                ('usertype', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age', models.IntegerField(max_length=100, null=True)),
                ('grade', models.IntegerField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('email', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.login')),
            ],
        ),
    ]
