# Generated by Django 4.1.5 on 2023-01-31 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reg',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='grade',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
