# Generated by Django 4.1.5 on 2023-02-09 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_login_email_alter_reg_age_alter_reg_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading', models.CharField(max_length=100, null=True)),
                ('dictation', models.CharField(max_length=100, null=True)),
                ('match', models.CharField(max_length=100, null=True)),
                ('comprehension', models.CharField(max_length=100, null=True)),
                ('fill', models.CharField(max_length=100, null=True)),
                ('count', models.CharField(max_length=100, null=True)),
                ('currency', models.CharField(max_length=100, null=True)),
                ('order', models.CharField(max_length=100, null=True)),
                ('arithmetic', models.CharField(max_length=100, null=True)),
                ('compare', models.CharField(max_length=100, null=True)),
                ('questionnaire', models.CharField(max_length=100, null=True)),
                ('result', models.CharField(max_length=100, null=True)),
                ('email', models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.login')),
            ],
        ),
    ]
