# Generated by Django 4.1.5 on 2023-02-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='arithmetic',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='compare',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='comprehension',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='count',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='currency',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='dictation',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='fill',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='match',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='order',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='questionnaire',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='reading',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='marks',
            name='result',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
