# Generated by Django 4.1.5 on 2023-02-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_marks_arithmetic_alter_marks_compare_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='email',
        ),
        migrations.AddField(
            model_name='marks',
            name='emailid',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
