# Generated by Django 4.1.5 on 2023-02-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_marks_email_marks_emailid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.EmailField(max_length=100, null=True)),
                ('reading', models.CharField(default='0', max_length=100)),
                ('dictation', models.CharField(default='0', max_length=100)),
                ('match', models.CharField(default='0', max_length=100)),
                ('comprehension', models.CharField(default='0', max_length=100)),
                ('fill', models.CharField(default='0', max_length=100)),
                ('count', models.CharField(default='0', max_length=100)),
                ('currency', models.CharField(default='0', max_length=100)),
                ('order', models.CharField(default='0', max_length=100)),
                ('arithmetic', models.CharField(default='0', max_length=100)),
                ('compare', models.CharField(default='0', max_length=100)),
                ('questionnaire', models.CharField(default='0', max_length=100)),
                ('result', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
